name: Metrics Base
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: CuriousCorrelation
          template: classic
          filename: metrics-base.svg
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata
