name: Metrics Base
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: CuriousCorrelation
          template: classic
          filename: metrics-base.svg
          base: header, repositories
          base_indepth: yes
          base_hireable: no
          base_skip: following, packages
          config_timezone: Asia/Kolkata

          # === Repository Settings ===
          plugin_repositories: yes
          plugin_repositories_featured: hoppscotch/hoppscotch
          plugin_repositories_order: pinned, random
          plugin_repositories_affiliations: owner, collaborator, organization_member
          repositories_affiliations: owner, collaborator, organization_member
          repositories_batch: 100

          # === Languages & Skills ===
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_analysis_timeout: 15

          # === Contributions ===
          plugin_calendar: yes
          plugin_calendar_limit: 1

          # === Customization ===
          config_animations: yes
          config_base64: yes
          config_padding: 0, 8 + 11%
          config_output: auto

          optimize: css, xml, svg
